

spring:
  data:
    jdbc:
      repositories:
        enabled: false
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://beeb.cgtnbiy5haje.ap-northeast-2.rds.amazonaws.com:3306/beeb_test?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul # ??? db connection url
    #    username: root # ??? db username
    #    password: qlqm&fhqp! # ??? db password
    #
    url: jdbc:mysql://localhost:3306/beeb_test?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul # ??? db connection url
    username: root # ??? db username
    password: 910314008 # ??? db password
#    #    ALTER user 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '910314008';
